name: Continous Integration / Continous Deployment

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  checkingComposer:
    name: Checking and Validate Composer
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, intl, bcmath, curl, mysql, zip
      - run: php -v
      - name: Validate composer.json and composer.lock file
        run: composer validate
      - name: Checking Composer Install Command
        run: composer update
  deploymentProduction:
    name: Update PRODUCTION
    runs-on: ubuntu-22.04
    needs: [checkingComposer]
    if: (success() && github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - name: Login SSH Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /root/apps/RWA-Pay
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan filament:optimize
            php artisan icon:cache
            php artisan octane:reload
            php artisan queue:restart
            sudo supervisorctl restart pay-octane
            sudo supervisorctl restart pay-queue:*
